'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empleados
    Public Property idempleados As Integer
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Id_Departamento As Integer

    Public Overridable Property departamentos As departamentos

End Class
