'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class templeados
    Public Property id As Integer
    Public Property nombre As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property departamento_id As Integer

    Public Overridable Property tdepartamento As tdepartamento

End Class
